name = "Zettlekasten"
uuid = "fa727ab4-b81a-47de-8fc7-13be6614b56f"
authors = ["gabrielle.gasse@gmail.com"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
